apiVersion: v1
kind: Service
metadata:
  name: ai-coworker
  labels:
    app.kubernetes.io/name: ai-coworker
spec:
  selector:
    app.kubernetes.io/name: ai-coworker
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
